version: '3'
services:
  postgres_db:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres-src:/var/lib/postgresql/data
    networks:
      - app-net

  backend:
    build: ./src/dck-b
    container_name: backend
    env_file:
      - .env
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - backend-src:/app
    networks:
      - app-net

  frontend:
    build: ./src/dck-f
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - frontend-src:/app
    networks:
      - app-net
  
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
     - '8080:8080'
    depends_on:
      - postgres_db
    networks:
      - app-net

volumes:
  backend-src:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .${PWD}/backend

  postgres-src:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .${PWD}/db

  frontend-src:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .${PWD}/frontend

networks:
  app-net:
    driver: bridge
