---
- name: Configuration and Provisioning of the VM with Ansible
  hosts: all
  gather_facts: no
  vars:
    ansible_ssh_user: yoyo
  tasks:
    # - name: Install Ansible
    #   become: yes
    #   apt:
    #     name: ansible
    #     state: present
    - name: Install Docker and Docker Compose
      become: yes
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker.io
        - docker-compose

    - name: Configure Docker logging
      become: yes
      lineinfile:
        path: /etc/docker/daemon.json
        line: '{"log-driver": "json-file", "log-opts": {"max-size": "100m"}}'
        create: yes

    - name: Set up a Cronjob for Docker cleanup
      become: yes
      copy:
        content: |
          0 3 * * * /usr/bin/docker system prune -af
        dest: /etc/cron.d/docker_cleanup
        mode: '0644'

    - name: Add user to Docker group
      become: yes
      user:
        name: "{{ ansible_ssh_user }}"
        groups: docker
        append: yes
    # - name: Transfer files to the target host
    #   become: yes
    #   synchronize:
    #     src: /home/yoyo/ci-cd/
    #     dest: /home/yoyo/
    #     mode: '0644'
    #     copy_links: yes  # Copy symbolic links as links
    - name: Transfer files to the target host
      become: yes
      synchronize:
        src: /home/yoyo/ci-cd/
        dest: /home/yoyo/
        perms: '0644'
        copy_links: yes  # Copy symbolic links as links


    # - name: Install Java
    #   become: yes
    #   apt:
    #     name: openjdk-11-jdk
    #     state: present

    # - name: Update apt cache
    #   become: yes
    #   apt:
    #     update_cache: yes

    # - name: Download Jenkins Debian repository key
    #   become: yes
    #   shell: wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -

    # - name: Import Jenkins GPG key
    #   become: yes
    #   apt_key:
    #     id: 5BA31D57EF5975CA
    #     keyserver: keyserver.ubuntu.com
    #     state: present

    # - name: Add Jenkins Debian repository
    #   become: yes
    #   apt_repository:
    #     repo: deb https://pkg.jenkins.io/debian-stable binary/
    #     state: present

    # - name: Update apt and install Jenkins
    #   become: yes
    #   apt:
    #     name: jenkins
    #     state: present
