---
- name: Configuration and Provisioning of the VM with Ansible
  hosts: all
  gather_facts: no
  vars:
    docker_registry: "192.168.100.75:5000"

  tasks:
    - name: Install Docker and Docker Compose
      become: yes
      apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: Configure Docker logging
      become: yes
      lineinfile:
        path: /etc/docker/daemon.json
        line: '{"log-driver": "json-file", "log-opts": {"max-size": "100m"}}'
        create: yes

    - name: Set up a Cronjob for Docker cleanup
      become: yes
      copy:
        content: |
          0 3 * * * /usr/bin/docker system prune -af
        dest: /etc/cron.d/docker_cleanup
        mode: '0644'

    - name: Add user to Docker group
      become: yes
      user:
        name: "{{ ansible_ssh_user }}"
        groups: docker
        append: yes

    - name: Create a directory for the application
      become: yes
      file:
        path: /home/yoyo/app
        state: directory

    - name: Clone application repository
      become: yes
      git:
        repo: https://github.com/yismaili/ci-cd
        dest: /home/yoyo/app

    - name: Build backend Docker image
      become: yes
      command: docker build -t backend:latest /home/yoyo/app/backend
      args:
        chdir: /home/yoyo/app

    - name: Build frontend Docker image
      become: yes
      command: docker build -t frontend:latest /home/yoyo/app/frontend
      args:
        chdir: /home/yoyo/app

    # - name: Pull backend Docker image
    #   docker_image:
    #     name: "{{ docker_registry }}/ci-cd:backend-a7de1d6-43"
    #     source: pull

    # - name: Pull frontend Docker image
    #   docker_image:
    #     name: "{{ docker_registry }}/ci-cd:frontend-a7de1d6-43"
    #     source: pull

