
---
- name: Configuration and Provisioning of the VM with Ansible
  hosts: all
  gather_facts: no
  vars:
    docker_registry: "192.168.100.75:5000" 
    volumes:
      backend-src: "/home/yoyo/app/backend"
      postgre: "/home/yoyo/app/postgres"
      frontend-src: "/home/yoyo/app/frontend"

  tasks:
    - name: Install Docker and Docker Compose
      become: yes
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker.io
        - docker-compose

    - name: Configure Docker logging
      become: yes
      lineinfile:
        path: /etc/docker/daemon.json
        line: '{"log-driver": "json-file", "log-opts": {"max-size": "100m"}}'
        create: yes

    - name: Set up a Cronjob for Docker cleanup
      become: yes
      copy:
        content: |
          0 3 * * * /usr/bin/docker system prune -af
        dest: /etc/cron.d/docker_cleanup
        mode: '0644'

    - name: Add user to Docker group
      become: yes
      user:
        name: "{{ ansible_ssh_user }}"
        groups: docker
        append: yes

    - name: Create a directory for application
      become: yes
      file:
        path: /home/yoyo/app
        state: directory

    - name: Clone application repository
      become: yes
      git:
        repo: https://github.com/yismaili/ci-cd
        dest: /home/yoyo/app

    - name: Create directories for volumes
      file:
        path: "{{ item.value }}"
        state: directory
      loop: "{{ volumes | dict2items }}"

    - name: Copy Docker Compose file
      copy:
        src: "{{ playbook_dir }}/docker-compose.yml"
        dest: "{{ ansible_user_dir }}/docker-compose.yml"

    - name: Run Docker Compose
      command: docker-compose up -d
      args:
        chdir: "{{ ansible_user_dir }}"
