
version: '3'
services:
  postgres_db:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres-src:/var/lib/postgresql/data
    networks:
      - app-net

  backend:
    image: localhost:5000/backend:1.0
    container_name: backend
    env_file:
      - .env
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - backend-src:/app
    networks:
      - app-net

  frontend:
    image: localhost:5000/frontend:1.0
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - frontend-src:/app
    networks:
      - app-net

volumes:
  backend-src:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/backend

  postgres-src:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/db

  frontend-src:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/frontend

networks:
  app-net:
    driver: bridge
