
version: '3'
services:
  postgres_db:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres-src:/var/lib/postgresql/data
    networks:
      - app-net

  # backend:
  #   build: ./src/dck-f
  #   container_name: backend
  #   env_file:
  #     - .env
  #   restart: always
  #   ports:
  #     - "3001:3001"
  #   volumes:
  #     - backend-src:/app
  #   networks:
  #     - app-net

  # frontend:
  #   build: ./src/dck-f
  #   container_name: frontend
  #   restart: always
  #   depends_on:
  #     - backend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - frontend-src:/app
  #   networks:
  #     - app-net

volumes:
  backend-src:
    driver: local
    driver_opts:
      type: none
      device: /home/yoyo/Desktop/web-coding-challenge/backend

  postgres-src:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/Desktop/web-coding-challenge/db

  frontend-src:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/Desktop/web-coding-challenge/frontend

networks:
  app-net:
    driver: bridge
