version: '3'
services:
  postgres_db:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    # volumes:
    #   - postgre:/var/lib/postgresql/data
    networks:
      - app-net

  backend:
    image: ${BACKEND_IMAGE}
    container_name: backend
    env_file:
      - .env
    restart: always
    ports:
      - "3001:3001"
    # volumes:
    #   - backend-src:/app
    networks:
      - app-net

  frontend:
    image: ${FRONTEND_IMAGE}
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    # volumes:
    #   - frontend-src:/app
    networks:
      - app-net

volumes:
  backend-src:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/backend

  postgre:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/postgres

  frontend-src:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/frontend

networks:
  app-net:
    driver: bridge

# # Create Docker volume for Jenkins data
# run_jenkins_data_volume:
#   command: sh -c 'docker volume create --opt type=none --opt device=/home/yoyo/Desktop/jenkins --opt o=bind jenkins-data'
#   image: docker:latest
#   volumes:
#     - /var/run/docker.sock:/var/run/docker.sock
#   entrypoint: ''
#   depends_on:
#     - postgres_db
#     - backend
#     - frontend
